### PR TITLE
loading indicator retro style

### PR DESCRIPTION
**Pull request by groupsky**
loading-indicator-retro-style

### CODE REVIEW

**Comment by ironsteel** [comment]
Hmm can we make that more pixelized :) ? Anyway I'm merging this because it's cool :+1:  Geno :)

**Comment by ironsteel** [comment]
One last question: How long does it takes to load ?

**Comment by groupsky** [comment]
@ironsteel couple of seconds until the events are loaded - we have very fast internet connection :smiling_imp:

**Comment by groupsky** [comment]
Build failed: https://app.wercker.com/#buildstep/56681472a93d3b7a79083641
​

**Comment by groupsky** [comment]
Build failed: https://app.wercker.com/#buildstep/56681472a93d3b7a79083641

**Pull request merged**
